
#-------------------------------------#
#         Explosive Projectiles       #
#                                     #
#             Sintax Labs             #
#-------------------------------------#
explosive-impact: 5
#Range 0-127
toggle-Fire: false
#Similar to Ghast fireball explosions.
toggle-BreakBlocks: true
#NOTE: If true, to prevent block-damage in WorldGuard Regions, set other-explosions to false in your Region Flags.
#/rg info regionName then Flags.
toggle-HurtMobs: 0
toggle-HurtPlayer: 0


#Projectile Items
#-------------------------------------
EGG: 0
BOW: 1
SNOWBALL: 0


#Miscellaneous Toggles
#-------------------------------------
verbose: 0
#For debugging. Not recommended for live servers.
Require-Permission: 0
#Only players with permission can trigger the explosion.
